version: '3.9'

services:
  app:
    build: .
    ports:
      - '80:80'
    environment:
      MYSQL_HOST: rdmdbhost
      MYSQL_USER: root
      MYSQL_PASSWORD: dbpass
      MYSQL_DATABASE: rdmdb
      PASSWORD: password

volumes:
  db-data:
